[CmdletBinding()]
param([string]$BuildDirectory = (Join-Path (Split-Path $PSScriptRoot -Parent) 'build\windows-release'))
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path $PSScriptRoot -Parent
$moduleTarget = Join-Path $BuildDirectory 'Mod\Fission'
New-Item -ItemType Directory -Force -Path $moduleTarget | Out-Null
$moduleSource = (Resolve-Path -LiteralPath (Join-Path $projectRoot 'Mod\Fission')).Path
foreach ($sourceFile in Get-ChildItem -LiteralPath $moduleSource -File -Recurse) {
    $relativePath = $sourceFile.FullName.Substring($moduleSource.Length + 1)
    if ($sourceFile.Extension -eq '.pyc' -or $relativePath.Split([IO.Path]::DirectorySeparatorChar) -contains '__pycache__') {
        continue
    }
    $destination = Join-Path $moduleTarget $relativePath
    New-Item -ItemType Directory -Force -Path (Split-Path $destination -Parent) | Out-Null
    Copy-Item -LiteralPath $sourceFile.FullName -Destination $destination -Force
}
# Reused runtimes must import the installed source, without carrying developer
# bytecode caches or their original source paths into the portable archive.
$moduleTargetFull = (Resolve-Path -LiteralPath $moduleTarget).Path
foreach ($cacheDirectory in Get-ChildItem -LiteralPath $moduleTargetFull -Directory -Recurse -Filter '__pycache__') {
    $cachePath = (Resolve-Path -LiteralPath $cacheDirectory.FullName).Path
    if (-not $cachePath.StartsWith($moduleTargetFull + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase) -or
        $cacheDirectory.LinkType) {
        throw 'Generated bytecode cache is outside the installed Fission module.'
    }
    Remove-Item -LiteralPath $cachePath -Recurse -Force
}
$binTarget = Join-Path $BuildDirectory 'bin'
New-Item -ItemType Directory -Force -Path $binTarget | Out-Null
@'
<?xml version="1.0" encoding="utf-8"?>
<Branding version="1.0">
  <Application>Fission</Application>
  <ExeName>Fission</ExeName>
  <ExeVendor>Fission</ExeVendor>
  <AppDataSkipVendor>true</AppDataSkipVendor>
  <WindowTitle>Fission</WindowTitle>
  <WindowIcon>fission</WindowIcon>
  <ProgramLogo>fission</ProgramLogo>
  <SplashScreen>fissionsplash</SplashScreen>
  <AboutImage>fissionsplash</AboutImage>
  <StartWorkbench>FissionWorkbench</StartWorkbench>
  <NavigationStyle>Gui::FissionNavigationStyle</NavigationStyle>
  <DesktopFileName>org.fission.Fission</DesktopFileName>
  <BuildRepositoryURL>https://github.com/pjourney/fission</BuildRepositoryURL>
  <CopyrightInfo>Fission is based on the FreeCAD open-source project. Original copyrights and licenses apply.</CopyrightInfo>
</Branding>
'@ | Set-Content -LiteralPath (Join-Path $binTarget 'branding.xml') -Encoding utf8
Write-Host "Fission presentation installed in $BuildDirectory"
